//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Esoft_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class СделкиSet
    {
        public int Id { get; set; }
        public int IdSupply { get; set; }
        public int IdDemand { get; set; }
    
        public virtual ПотребностиSet ПотребностиSet { get; set; }
        public virtual ПредложенияSet ПредложенияSet { get; set; }
    }
}
